blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Mentor Discussion
    url: https://github.com/aslavchev/qa-mentorship-program/discussions
    about: General questions or discussions with your mentor
  - name: ðŸ“š QA Fundamentals Documentation
    url: https://github.com/aslavchev/qa-mentorship-program/blob/main/README.md
    about: Program overview, weekly curriculum, and getting started
